/*
 * kearch specialist search engine gateway API
 *
 * kearch specialist search engine gateway API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Document struct {

	Url string `json:"url,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty"`

	Score float32 `json:"score,omitempty"`
}
