/*
 * kearch specialist search engine gateway API
 *
 * kearch specialist search engine gateway API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Summary struct {

	SpHost string `json:"sp_host,omitempty"`

	EngineName string `json:"engine_name,omitempty"`

	Dump map[string]int32 `json:"dump,omitempty"`
}
